# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbd-test1',
                'doc_host': 'https://anasbraj.github.io',
                'git_url': 'https://github.com/anasbraj/nbd-test1',
                'lib_path': 'nbd_test1'},
  'syms': {'nbd_test1.core': {'nbd_test1.core.foo': ('core.html#foo', 'nbd_test1/core.py')}}}