# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_another.ipynb.

# %% auto 0
__all__ = ['Another', 'AnoterOne']

# %% ../nbs/02_another.ipynb 1
class Another():
    def __init__(self) -> None:
        print("another")

# %% ../nbs/02_another.ipynb 3
class AnoterOne():
    def __init__(self) -> None:
        print("another one")
