# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_book.ipynb.

# %% auto 0
__all__ = ['Book']

# %% ../nbs/01_book.ipynb 2
import pandas as pd

# %% ../nbs/01_book.ipynb 4
class Book:
    def __init__(self, title, author, price):
        self.title = title
        self.author = author
        self.price = price
    
    def __str__(self):
        return "str rep"
    
    __repr__ = __str__
