# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_my.ipynb.

# %% auto 0
__all__ = ['add']

# %% ../nbs/01_my.ipynb 3
# actually add something
def add(a, b):
    res = a + b
    print(f"{a} + {b} = {res}")
    return res
